Load Dataset File

In [116]:
# Imports
from PIL import Image
import torch
import torch.nn as nn  # All neural network modules, nn.Linear, nn.Conv2d, BatchNorm, Loss functions
import torch.optim as optim  # For all Optimization algorithms, SGD, Adam, etc.
import torchvision.transforms as transforms  # Transformations we can perform on our dataset
import torchvision
import os
import pandas as pd
from skimage import io
# from sys.path.append("/Users/jordbeek/Documents/Artificial Intelligence/Year 3/BP/CNN/Resnet CNN.ipynb") import ResNet
%run "Resnet CNN.py"

from torch.utils.data import (
    Dataset,
    DataLoader,
)  # Gives easier dataset managment and creates mini batches

# HERE BELOW: ALTER FOR PERSONAL DATASET
class DeforestationDataset(Dataset):
    def __init__(self, csv_file, root_dir, transform=None):
        self.annotations = pd.read_csv(csv_file, header=None, names=['file_name', 'loss'])
        self.root_dir = root_dir
        self.transform = transform
        self.all_images = os.listdir(self.root_dir)
        

    def __len__(self):
#         return len(self.annotations) #23865
       return len(os.listdir(self.root_dir)) 
    
    def __getitem__(self, index):
        name = self.all_images[index]
        image = io.imread(os.path.join(self.root_dir, name))[..., :3]
        
        # name_in_DSLabel = self.annotations.iloc[index, 0]
        # Loss Label_9_3.tif
        # Last - Edit_97_31.tif
#         name = 'Last - Edit' + name_in_DSLabel.split('l')[-1]
#         print(name_in_DSLabel)
#         print(name)
#         img_path = os.path.join(self.root_dir, name)
#         image = io.imread(img_path)
#         image = Image.open(img_path)
#         y_label = torch.tensor(int(self.annotations.iloc[index, 1]))

        if self.transform:
            image = self.transform(image)

            
        name_in_csv = 'Loss Label' + name[11:]        
        y_label = torch.tensor(float(self.annotations['loss'][annotations['file_name'] == name_in_csv]), dtype=torch.float)

        return (image, y_label)


# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Hyperparameters
in_channel = 3
num_classes = 2
learning_rate = 1e-3
batch_size = 4
num_epochs = 10

# Load Data
labels_csv = open('/Users/jordbeek/Documents/Artificial Intelligence/Year 3/BP/Datasets/Global Deforestation/Bolivia East//Labels.csv')
deforestation_train_dir = ('/Users/jordbeek/Documents/Artificial Intelligence/Year 3/BP/Datasets/Global Deforestation/Bolivia East/TrainSet/')
deforestation_test_dir = ('/Users/jordbeek/Documents/Artificial Intelligence/Year 3/BP/Datasets/Global Deforestation/Bolivia East/TestSet/')
train_dataset = DeforestationDataset(
    csv_file=labels_csv, 
    root_dir=deforestation_train_dir, 
    transform=transforms.ToTensor(),
)


# train_set, test_set = torch.utils.data.random_split(dataset, [5, 5]) # split dataset -- not necessary
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
# test_loader = DataLoader(dataset=dataset, batch_size=batch_size, shuffle=True)


# Model
model = ResNet50(img_channels=3) #
model.to(device) # lisa?

# Loss and optimizer
# criterion = nn.CrossEntropyLoss() # Regression: mean squared error loss
criterion = nn.MSELoss() 
optimizer = optim.Adam(model.parameters(), lr=learning_rate) # Gradient Descent?

# Train Network
for epoch in range(num_epochs):
    losses = []

    for batch_idx, (data, targets) in enumerate(train_loader):
        
        # Get data to cuda if possible
        data = data.to(device=device)
        targets = targets.to(device=device)

        # forward
        scores = model(data)
        print(scores.shape)
        print(targets.shape)
        loss = criterion(scores, targets)
        print(scores[0])
        print(targets[0])
        losses.append(loss.item())

        # backward
        optimizer.zero_grad()
        loss.backward()

        # gradient descent or adam step
        optimizer.step()

    print(f"Cost at epoch {epoch} is {sum(losses)/len(losses)}")

# Check accuracy on training to see how good our model is
def check_accuracy(loader, model):
    num_correct = 0
    num_samples = 0
    model.eval()

    with torch.no_grad():
        for x, y in loader:
            x = x.to(device=device)
            y = y.to(device=device)

            scores = model(x)
            _, predictions = scores.max(1)
            num_correct += (predictions == y).sum()
            num_samples += predictions.size(0)

        print(
            f"Got {num_correct} / {num_samples} with accuracy {float(num_correct)/float(num_samples)*100:.2f}"
        )

    model.train()


print("Checking accuracy on Training Set")
check_accuracy(train_loader, model)

print("Checking accuracy on Test Set")
check_accuracy(test_loader, model)

NameError: name 'test' is not defined

torch.Size([4, 1])
torch.Size([4])
tensor([-0.5200], grad_fn=<SelectBackward0>)
tensor(0.0100)
torch.Size([4, 1])
torch.Size([4])
tensor([-0.7525], grad_fn=<SelectBackward0>)
tensor(0.)
torch.Size([4, 1])
torch.Size([4])
tensor([1.1379], grad_fn=<SelectBackward0>)
tensor(0.0300)
torch.Size([4, 1])
torch.Size([4])
tensor([-0.0660], grad_fn=<SelectBackward0>)
tensor(0.3200)
torch.Size([4, 1])
torch.Size([4])
tensor([-0.6605], grad_fn=<SelectBackward0>)
tensor(0.3300)
torch.Size([4, 1])
torch.Size([4])
tensor([4.1858], grad_fn=<SelectBackward0>)
tensor(0.0900)
torch.Size([4, 1])
torch.Size([4])
tensor([1.7919], grad_fn=<SelectBackward0>)
tensor(0.0300)


KeyboardInterrupt: 

In [ ]:
train_loader

In [23]:
enumerate(train_loader)

In [79]:
labels_csv = open('/Users/jordbeek/Documents/Artificial Intelligence/Year 3/BP/Datasets/Global Deforestation/Bolivia East/Labels.csv')

In [80]:
annotations = pd.read_csv(labels_csv, header=None, names=['file_name', 'loss'])

In [81]:
annotations

file_name  loss
0         Loss Label_74_1.tif  0.32
1       Loss Label_88_152.tif  0.09
2      Loss Label_113_108.tif  0.04
3       Loss Label_110_48.tif  0.48
4        Loss Label_28_28.tif  0.11
...                       ...   ...
23859     Loss Label_67_6.tif  0.06
23860    Loss Label_41_87.tif  0.17
23861  Loss Label_113_111.tif  0.12
23862    Loss Label_28_31.tif  0.11
23863   Loss Label_110_51.tif  0.16

[23864 rows x 2 columns]

In [82]:
annotations['file_name']

0           Loss Label_74_1.tif
1         Loss Label_88_152.tif
2        Loss Label_113_108.tif
3         Loss Label_110_48.tif
4          Loss Label_28_28.tif
                  ...          
23859       Loss Label_67_6.tif
23860      Loss Label_41_87.tif
23861    Loss Label_113_111.tif
23862      Loss Label_28_31.tif
23863     Loss Label_110_51.tif
Name: file_name, Length: 23864, dtype: object

In [93]:
annotations

file_name  loss
0         Loss Label_74_1.tif  0.32
1       Loss Label_88_152.tif  0.09
2      Loss Label_113_108.tif  0.04
3       Loss Label_110_48.tif  0.48
4        Loss Label_28_28.tif  0.11
...                       ...   ...
23859     Loss Label_67_6.tif  0.06
23860    Loss Label_41_87.tif  0.17
23861  Loss Label_113_111.tif  0.12
23862    Loss Label_28_31.tif  0.11
23863   Loss Label_110_51.tif  0.16

[23864 rows x 2 columns]

In [97]:
annotations['loss'][annotations['file_name'] == 'Loss Label_74_1.tif']

0    0.32
Name: loss, dtype: float64

In [88]:
a[10:]

't_124_153.tif'

In [89]:
a[11:]

'_124_153.tif'